### ISSUE TITLE
Possible problem at static-content:deploy stage (production mode)

### ISSUE THREAD

**Issue by rbayet** [mageplaza/magento-2-dutch-language-pack#1]
Hi,

Context: 
multi-language environment (en_US, fr_FR, nl_NL).
EE 2.1.5
mageplaza/module-core: 1.3.1
language pack version: 1.0.0

In production mode, when deploying the nl_NL language (after having deployed en_US and nl_NL) with :
```
./bin/magento setup:static-content:deploy --jobs 8 nl_NL
```

the following error occurs 
```
Processing file 'magnifier/magnify.js' for area 'adminhtml', theme 'Magento/backend', locale 'nl_NL'
	Deploying the file to 'adminhtml/Magento/backend/nl_NL/magnifier/magnify.js'
Processing file 'js-translation.json' for area 'adminhtml', theme 'Magento/backend', locale 'nl_NL'
	Deploying the file to 'adminhtml/Magento/backend/nl_NL/js-translation.json'
.#0 [internal function]: Magento\Framework\App\ErrorHandler->handler(8, 'unserialize(): ...', '/var/www/projec...', 477, Array)
#1 /var/www/project/releases/0.0.0.18/vendor/magento/framework/Translate.php(477): unserialize('+OK')
#2 /var/www/project/releases/0.0.0.18/vendor/magento/framework/Translate.php(172): Magento\Framework\Translate->_loadCache()
```
No problem encountered when deploying the en_US and fr_FR languages (we do use the magento2-french-language-pack submodule).

Disabling the Mageplaza_Core module itself solved the problem.

Regards

**Comment by imsamthomas** [comment]
Hi,

It's quite strange because there is no error related to `Mageplaza_Core`.
I will notice our technical team and look into this for further information.

Regards,
Sam

**Comment by imsamthomas** [comment]
Hi @goodluckrememberingthisone ,
Can you please attach the file `adminhtml/Magento/backend/nl_NL/js-translation.json`
We will investigate the issue.
It seems Magento core issue.

**Comment by zebeel** [comment]
Close due to no response in 7 days
