### ISSUE TITLE
Spelling error telefonish - should be telefonisch

### ISSUE THREAD

**Issue by bamboekeizer** [mageplaza/magento-2-dutch-language-pack#14]
The order emails contain a spelling error. In two occurences in the translation file the word telefonish should be replaced by telefonisch

**Comment by lvgreay** [comment]
> 
> 
> The order emails contain a spelling error. In two occurences in the translation file the word telefonish should be replaced by telefonisch

That's right! please change it. 
Thank you in advance.

**Comment by bamboekeizer** [comment]
Update github_contributions.csv #15
Correct spelling error telefonish to telefonisch

mageplaza:master ← bamboekeizer:patch-1

**Comment by vandijkstef** [comment]
I couldn't find this anymore, can we close this?

**Comment by bamboekeizer** [comment]
Yes, the change has been incorporated
