### ISSUE TITLE
Conflict with one step checkout module

### ISSUE THREAD

**Issue by Bram-Zijp** [mageplaza/magento-2-dutch-language-pack#4]
Hi I just installed this through composer and my website broke. I can't get it uninstalled. How do you remove this as it conflict with the premium One Page Checkout plugin.

There were duplicates found in Composer therefor I couldnt do anything.

My website returns error 500.

**Comment by imsamthomas** [comment]
Hi,

You can follow this guide to resolve it
https://github.com/mageplaza/module-core/issues/3

If you cannot resolve it yourself, feel free to get help at
https://mageplaza.freshdesk.com

Regards,
Sam

**Comment by Bram-Zijp** [comment]
Hi Sam, That guide didn't resolve and I submitted a ticket at megaplaza.freshdesk.com

**Comment by imsamthomas** [comment]
I see.
It is out of working time now.
I will ask our supporter disable it temporary, we will look into this
tomorrow.
